Use mount(8) for the temporary mount.
This means we don't need to muck about with the mountpoint attribute.
It's perfectly safe to do this, since the new root is unmounted and has
canmount=noauto by this point.

diff --git a/beadm b/beadm
--- a/beadm
+++ b/beadm
@@ -223,66 +223,61 @@ case ${1} in
     then
       __usage
     fi
-    __be_exist ${POOL}/ROOT/${2}
-    if [ "${BOOTFS}" = "${POOL}/ROOT/${2}" ]
+    NEWROOT="${POOL}/ROOT/${2}"
+    __be_exist "${NEWROOT}"
+    if [ "${BOOTFS}" = "${NEWROOT}" ]
     then
       echo "Already activated"
       exit 0
     else
-      if [ "${ROOTFS}" != "${POOL}/ROOT/${2}" ]
+      if [ "${ROOTFS}" != "${NEWROOT}" ]
       then
-        TMPMNT="/tmp/BE"
-        if ! mkdir -p ${TMPMNT}
+        + zfs set canmount=noauto "${NEWROOT}"
+        if [ $(zfs list -Ho mounted "${NEWROOT}") = yes ]
         then
-          echo "ERROR: Cannot create '${TMPMNT}' directory"
-          exit 1
+            + zfs umount "${NEWROOT}"
         fi
-        MOUNT=0
-        while read FS MNT
-        do
-          if [ "${FS}" = "${POOL}/ROOT/${2}" ]
-          then
-            MOUNT=${MNT}
-          fi
-        done << EOF
-$( mount -p | awk '{print $1 " " $2}' )
-EOF
-        if [ ${MOUNT} -eq 0 ]
-        then
-          + zfs set canmount=noauto ${POOL}/ROOT/${2}
-          + zfs set mountpoint=${TMPMNT} ${POOL}/ROOT/${2}
-          + zfs mount ${POOL}/ROOT/${2} 1> /dev/null 2> /dev/null
-        else
-          TMPMNT=${MOUNT}
-        fi
+
+        TMPMNT=$(mktemp -dt beadm)
+        # Use mount(8) rather than zfs(1) since this is just a temporary
+        # mount. We've just set canmount=noauto and made sure the FS is
+        # unmounted, so this is safe.
+        + mount -t zfs "${NEWROOT}" "${TMPMNT}"
         + cp /boot/zfs/zpool.cache ${TMPMNT}/boot/zfs/zpool.cache # 2> /dev/null
+
         LOADER_CONFIGS=${TMPMNT}/boot/loader.conf
         if [ -f ${TMPMNT}/boot/loader.conf.local ]
         then
           LOADER_CONFIGS="${LOADER_CONFIGS} ${TMPMNT}/boot/loader.conf.local"
-          fi
-        + sed -i '' -E s/"^vfs.root.mountfrom=.*$"/"vfs.root.mountfrom=\"zfs:${POOL}\/ROOT\/${2##*/}\""/g ${LOADER_CONFIGS} 2> /dev/null
-        if [ ${MOUNT} -eq 0 ]
-        then
-          + zfs umount ${POOL}/ROOT/${2}
-          + zfs set mountpoint=legacy ${POOL}/ROOT/${2}
         fi
+        + sed -i '' -E s/"^vfs.root.mountfrom=.*$"/"vfs.root.mountfrom=\"zfs:${POOL}\/ROOT\/${2##*/}\""/g ${LOADER_CONFIGS} 2> /dev/null
+
+        + umount ${TMPMNT}
+        rmdir ${TMPMNT}
+        # The correct settings for a root fs are canmount=noauto,
+        # mountpoint=/. The old recommendation of mountpoint=legacy
+        # causes problems with subordinate fsen which expect to inherit
+        # their mountpoint, which is why Sun introduced the canmount
+        # property in the first place. Since the fs is currently
+        # unmounted, changing mountpoint will not cause zfs(1) to remount
+        # the fs over the current root.
+        + zfs set mountpoint=/ ${NEWROOT}
       fi
-      if ! + zpool set bootfs=${POOL}/ROOT/${2} ${POOL}
+      if ! + zpool set bootfs=${NEWROOT} ${POOL}
       then
-        echo "ERROR: Failed to activate '${POOL}/ROOT/${2}'"
+        echo "ERROR: Failed to activate '${NEWROOT}'"
         exit 1
       fi
     fi
     # Disable mounting on all inactive datasets
     zfs list -H -o name -r ${POOL}/ROOT \
-      | grep -v "${POOL}/ROOT/${2}" \
+      | grep -v "${NEWROOT}" \
       | while read I
         do
           + zfs set canmount=noauto ${I}
         done
     # Enable mounting for the active BE and promote it
-    zfs list -H -o name,origin -t filesystem -r ${POOL}/ROOT/${2} \
+    zfs list -H -o name,origin -t filesystem -r ${NEWROOT} \
       | while read I ORIGIN
         do
           + zfs set canmount=on ${I}
